### ISSUE TITLE
Default node does not support PoW

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/gh-tangle-release#3]
The default node, `https://nodes.iota.org:443`, does not support remote PoW. We should specify another node instead (e.g. `https://nodes.thetangle.org:443` or `https://nodes.iota.cafe:443`)

**Comment by obany** [comment]
Fixed https://github.com/iotaledger/gh-tangle-release/commit/de0c0cc9aa8d7fa84552cadc33ba1f106c361d5d
