### ISSUE TITLE
[CLI] missing required parameters returns help with no message

### ISSUE THREAD

**Issue by jbolda** [iotaledger/gh-tangle-release#7]
If you run the command and do not include an option that is required, then it will just return the help menu with no additional context. The help menu also does not note which parameters are required.

![image](https://user-images.githubusercontent.com/2019387/89298326-ca58a900-d62a-11ea-81be-2feff8fe012f.png)

**Comment by obany** [comment]
Fixed in https://github.com/iotaledger/gh-tangle-release/releases/tag/v0.7.1
