### ISSUE TITLE
[CLI] specify options through envs

### ISSUE THREAD

**Issue by jbolda** [iotaledger/gh-tangle-release#8]
Would you be interested in allowing some of the CLI options to be specified through environment variables? Particularly the github token is convenient to pull in from the envs, and possibly the seed.

**Comment by rajivshah3** [comment]
An easy way to do this would be to specify the environment variable as the default value for a certain option:

```js
.option("--mwm <number>",
        chalk.yellowBright("Minimum weight magnitude to use for attaching the transaction to the tangle"),
        process.env.MWM || "14")
```
However, an unintended consequence is that if `MWM=18` (for example) is defined, it will be shown as the default value in help:

```
--mwm <number>              Minimum weight magnitude to use for
                              attaching the transaction to the tangle
                              (default: "18")
```

**Comment by rajivshah3** [comment]
Actually, I think it would be better to have our own validation since the approach using `commander` has that weird side effect. We'd have to manually document which environment variables can be used anyway (`commander` doesn't really support environment variables)

**Comment by jbolda** [comment]
My main concern is that avoid accidentally printing secrets to a CLI log, etc. Theoretically they will be scrubbed, but rather not rely on that.

**Comment by rajivshah3** [comment]
Good point. In that case we should definitely use our own validation instead of the default value "hack" to reduce the chance that it's printed out

**Comment by obany** [comment]
QQ should we try and automatically pickup the `GITHUB_REPOSITORY` and `GITHUB_REF` env vars when using the CLI (like the action does), or is this going to cause confusion ?

Or should we instead define our own more specific env vars e.g. `GTR_RESPOSITORY` `GTR_REF` ?

**Comment by jbolda** [comment]
I don't see any issue with picking them up like the action does especially if you can specify them and that takes precedence.

**Comment by obany** [comment]
Added support for env vars in https://github.com/iotaledger/gh-tangle-release/releases/tag/v0.7.1
